import os
import sqlite3
import json
from pathlib import Path

import pytest

from zotero_project_manager.collections import build_collection_forest, resolve_collection
from zotero_project_manager.exporter import CollectionExporter, ExportError
from zotero_project_manager.manifest import load_manifest
from zotero_project_manager.zotero import ZoteroDatabase


def test_recursive_export_and_incremental_update(tmp_path: Path, zotero_fixture: object) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        forest = build_collection_forest(records)
        selected = resolve_collection(records, "My-AI")
        exporter = CollectionExporter(database, output)

        first = exporter.export_many([selected], forest)[0]
        assert first.copied == 2
        assert first.unchanged == 0
        workspace = output / "My-AI"
        assert (workspace / "Vaswani - 2017 - Attention Is All You Need.pdf").is_file()
        assert (workspace / "Books" / "Chollet - 2021 - Deep Learning with Python.pdf").is_file()

        second = exporter.export_many([selected], forest)[0]
        assert second.unchanged == 2
        assert second.copied == 0

        fixture.first_pdf.write_bytes(b"changed-content")  # type: ignore[attr-defined]
        os.utime(fixture.first_pdf, None)  # type: ignore[attr-defined]
        third = exporter.export_many([selected], forest)[0]
        assert third.updated == 1
        assert third.unchanged == 1
        assert len(load_manifest(workspace / ".zpm" / "manifest.json").items) == 2  # type: ignore[union-attr]
        assert load_manifest(workspace / ".zpm" / "manifest.json").items[0].source_sha256  # type: ignore[union-attr]
        assert "PDF count: 2" in (workspace / ".zpm" / "export-summary.md").read_text(encoding="utf-8")


def test_export_generates_metadata_json_and_markdown_index(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    workspace = output / "My-AI"
    payload = json.loads((workspace / ".zpm" / "metadata.json").read_text(encoding="utf-8"))
    assert payload["generated_by"] == "zpm"
    assert payload["schema_version"] == 1
    assert len(payload["items"]) == 2
    attention = next(item for item in payload["items"] if item["attachment_key"] == "ATTACH02")
    assert attention["doi"] == "10.5555/attention"
    assert attention["tags"] == ["AI"]
    assert attention["sha256"]

    index = (workspace / ".zpm" / "INDEX.md").read_text(encoding="utf-8")
    assert "Generated by zpm" in index
    assert "https://doi.org/10.5555/attention" in index
    assert "AI" in index


def test_metadata_generation_can_be_disabled(tmp_path: Path, zotero_fixture: object) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        CollectionExporter(database, output, export_metadata=False).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )
    assert not (output / "My-AI" / ".zpm" / "metadata.json").exists()
    assert not (output / "My-AI" / ".zpm" / "INDEX.md").exists()


def test_non_pdf_readme_exports_without_control_file_collision(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    source = fixture.data_dir / "storage" / "README01" / "README.md"  # type: ignore[attr-defined]
    source.parent.mkdir(parents=True)
    source.write_text("# Personal research project\n", encoding="utf-8")
    connection = sqlite3.connect(fixture.database)  # type: ignore[attr-defined]
    connection.execute("INSERT INTO items (itemID, key) VALUES (?, ?)", (300, "README01"))
    connection.execute("INSERT INTO collectionItems VALUES (?, ?)", (1, 300))
    connection.execute(
        "INSERT INTO itemAttachments VALUES (?, ?, ?, ?)",
        (300, None, "text/markdown", "storage:README.md"),
    )
    connection.execute("INSERT INTO itemDataValues VALUES (?, ?)", (6, "README"))
    connection.execute("INSERT INTO itemData VALUES (?, ?, ?)", (300, 1, 6))
    connection.commit()
    connection.close()

    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        CollectionExporter(database, output, include_non_pdf=True).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )

    workspace = output / "My-AI"
    assert (workspace / "README.md").read_text(encoding="utf-8") == "# Personal research project\n"
    assert (workspace / ".zpm" / "manifest.json").is_file()
    index = (workspace / ".zpm" / "INDEX.md").read_text(encoding="utf-8")
    assert "[MD](../README.md)" in index


def test_legacy_root_control_files_migrate_to_dot_zpm(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    workspace = output / "My-AI"
    control = workspace / ".zpm"
    (control / "manifest.json").replace(workspace / "manifest.json")
    (control / "metadata.json").replace(workspace / "metadata.json")
    (control / "INDEX.md").replace(workspace / "INDEX.md")
    (control / "export-summary.md").replace(workspace / "README.md")
    control.rmdir()

    source = fixture.data_dir / "storage" / "README01" / "README.md"  # type: ignore[attr-defined]
    source.parent.mkdir(parents=True)
    source.write_text("# Migrated personal project\n", encoding="utf-8")
    connection = sqlite3.connect(fixture.database)  # type: ignore[attr-defined]
    connection.execute("INSERT INTO items (itemID, key) VALUES (?, ?)", (300, "README01"))
    connection.execute("INSERT INTO collectionItems VALUES (?, ?)", (1, 300))
    connection.execute(
        "INSERT INTO itemAttachments VALUES (?, ?, ?, ?)",
        (300, None, "text/markdown", "storage:README.md"),
    )
    connection.execute("INSERT INTO itemDataValues VALUES (?, ?)", (6, "README"))
    connection.execute("INSERT INTO itemData VALUES (?, ?, ?)", (300, 1, 6))
    connection.commit()
    connection.close()
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        CollectionExporter(database, output, include_non_pdf=True).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )

    assert (workspace / ".zpm" / "manifest.json").is_file()
    assert (workspace / ".zpm" / "metadata.json").is_file()
    assert (workspace / ".zpm" / "INDEX.md").is_file()
    assert (workspace / ".zpm" / "export-summary.md").is_file()
    assert not (workspace / "manifest.json").exists()
    assert not (workspace / "metadata.json").exists()
    assert not (workspace / "INDEX.md").exists()
    assert (workspace / "README.md").read_text(encoding="utf-8") == (
        "# Migrated personal project\n"
    )


def test_export_generates_annotation_and_child_note_markdown(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        stats = CollectionExporter(database, output, export_annotations=True).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )[0]

    annotation_path = (
        output
        / "My-AI"
        / "Annotations"
        / "Books"
        / "Chollet - 2021 - Deep Learning with Python.md"
    )
    content = annotation_path.read_text(encoding="utf-8")
    assert stats.annotation_files == 2
    assert stats.annotations == 1
    assert stats.notes == 1
    assert "Page 4 — Highlight" in content
    assert "> Neural networks learn useful representations." in content
    assert "Connect this to the current model." in content
    assert "Reading notes" in content
    assert "Compare models" in content
    assert "zotero://open-pdf/library/items/ATTACH01?annotation=ANNOT001" in content


def test_unchanged_annotation_markdown_is_not_rewritten(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        selected = resolve_collection(records, "My-AI")
        forest = build_collection_forest(records)
        exporter = CollectionExporter(database, output, export_annotations=True)
        exporter.export_many([selected], forest)
        annotation_path = (
            output
            / "My-AI"
            / "Annotations"
            / "Books"
            / "Chollet - 2021 - Deep Learning with Python.md"
        )
        fixed_time = 1_700_000_000_000_000_000
        os.utime(annotation_path, ns=(fixed_time, fixed_time))
        exporter.export_many([selected], forest)
    assert annotation_path.stat().st_mtime_ns == fixed_time


@pytest.mark.parametrize(
    ("layout", "pdf_path", "annotation_path"),
    [
        (
            "sidecar",
            Path("Books/Chollet - 2021 - Deep Learning with Python.pdf"),
            Path("Books/Chollet - 2021 - Deep Learning with Python.annotations.md"),
        ),
        (
            "bundle",
            Path(
                "Books/Chollet - 2021 - Deep Learning with Python/"
                "Chollet - 2021 - Deep Learning with Python.pdf"
            ),
            Path("Books/Chollet - 2021 - Deep Learning with Python/annotations.md"),
        ),
    ],
)
def test_annotation_layout_controls_workspace_structure(
    tmp_path: Path,
    zotero_fixture: object,
    layout: str,
    pdf_path: Path,
    annotation_path: Path,
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        CollectionExporter(
            database,
            output,
            export_annotations=True,
            annotation_layout=layout,
        ).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )

    workspace = output / "My-AI"
    assert (workspace / pdf_path).is_file()
    assert (workspace / annotation_path).is_file()
    manifest = load_manifest(workspace / ".zpm" / "manifest.json")
    assert manifest is not None
    assert manifest.annotation_layout == layout


def test_existing_workspace_rejects_annotation_layout_change(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        with pytest.raises(ExportError, match="Workspace uses annotation layout"):
            CollectionExporter(database, output, annotation_layout="sidecar").export_many(
                [resolve_collection(records, "My-AI")], build_collection_forest(records)
            )


def test_annotation_export_refuses_unmanaged_markdown(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    unmanaged = (
        output
        / "My-AI"
        / "Annotations"
        / "Books"
        / "Chollet - 2021 - Deep Learning with Python.md"
    )
    unmanaged.parent.mkdir(parents=True)
    unmanaged.write_text("personal notes\n", encoding="utf-8")

    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        with pytest.raises(ExportError, match="unmanaged annotation"):
            CollectionExporter(database, output, export_annotations=True).export_many(
                [resolve_collection(records, "My-AI")], build_collection_forest(records)
            )
    assert unmanaged.read_text(encoding="utf-8") == "personal notes\n"


def test_filename_template_controls_new_workspace_names(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        CollectionExporter(
            database, output, filename_template="year_author_title"
        ).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )
    assert (output / "My-AI" / "2017 - Vaswani - Attention Is All You Need.pdf").is_file()
    manifest = load_manifest(output / "My-AI" / ".zpm" / "manifest.json")
    assert manifest is not None
    assert manifest.filename_template == "year_author_title"


def test_existing_workspace_rejects_filename_template_change(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        with pytest.raises(ExportError, match="Workspace uses filename template"):
            CollectionExporter(
                database, output, filename_template="year_author_title"
            ).export_many(
                [resolve_collection(records, "My-AI")], build_collection_forest(records)
            )


def test_refuses_to_replace_unmanaged_metadata_artifact(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        CollectionExporter(database, output, export_metadata=False).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )
    metadata_path = output / "My-AI" / ".zpm" / "metadata.json"
    metadata_path.parent.mkdir(exist_ok=True)
    metadata_path.write_text('{"personal": true}\n', encoding="utf-8")

    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        with pytest.raises(ExportError, match="unmanaged metadata"):
            CollectionExporter(database, output).export_many(
                [resolve_collection(records, "My-AI")], build_collection_forest(records)
            )
    assert json.loads(metadata_path.read_text(encoding="utf-8")) == {"personal": True}


def test_dry_run_writes_nothing(tmp_path: Path, zotero_fixture: object) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        stats = CollectionExporter(database, output, dry_run=True).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )[0]
    assert stats.copied == 2
    assert not output.exists()


def test_refuses_output_inside_zotero(zotero_fixture: object) -> None:
    fixture = zotero_fixture
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        with pytest.raises(ExportError):
            CollectionExporter(database, fixture.data_dir / "exports")  # type: ignore[attr-defined]


def test_unmanaged_workspace_requires_overwrite(tmp_path: Path, zotero_fixture: object) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    (output / "My-AI").mkdir(parents=True)
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        exporter = CollectionExporter(database, output)
        with pytest.raises(ExportError, match="not managed"):
            exporter.export_many(
                [resolve_collection(records, "My-AI")], build_collection_forest(records)
            )


def test_missing_source_keeps_prior_manifest_entry(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        exporter = CollectionExporter(database, output)
        selected = resolve_collection(records, "My-AI")
        forest = build_collection_forest(records)
        exporter.export_many([selected], forest)
        fixture.first_pdf.unlink()  # type: ignore[attr-defined]
        stats = exporter.export_many([selected], forest)[0]

    manifest = load_manifest(output / "My-AI" / ".zpm" / "manifest.json")
    assert stats.missing == 1
    assert manifest is not None
    assert len(manifest.items) == 2


def test_rejects_collection_directory_symlink_escape(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    workspace = output / "My-AI"
    workspace.mkdir(parents=True)
    outside = tmp_path / "outside"
    outside.mkdir()
    (workspace / "Books").symlink_to(outside, target_is_directory=True)
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        exporter = CollectionExporter(database, output, overwrite=True)
        with pytest.raises(ExportError, match="outside the workspace"):
            exporter.export_many(
                [resolve_collection(records, "My-AI")], build_collection_forest(records)
            )


def test_verify_detects_destination_tampering_with_preserved_metadata(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        selected = resolve_collection(records, "My-AI")
        forest = build_collection_forest(records)
        CollectionExporter(database, output).export_many([selected], forest)

    destination = output / "My-AI" / "Vaswani - 2017 - Attention Is All You Need.pdf"
    stat = destination.stat()
    destination.write_bytes(b"X" * stat.st_size)
    os.utime(destination, ns=(stat.st_atime_ns, stat.st_mtime_ns))

    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        stats = CollectionExporter(database, output, verify_hashes=True).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )[0]
    assert stats.updated == 1
    assert destination.read_bytes() == fixture.second_pdf.read_bytes()  # type: ignore[attr-defined]


def test_prune_deletes_only_hash_verified_removed_file(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    destination = output / "My-AI" / "Vaswani - 2017 - Attention Is All You Need.pdf"
    _remove_root_item(fixture.database)  # type: ignore[attr-defined]

    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        stats = CollectionExporter(database, output, prune=True).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )[0]

    assert stats.removed == 1
    assert stats.pruned == 1
    assert stats.protected == 0
    assert not destination.exists()


def test_prune_dry_run_never_deletes_or_rewrites_manifest(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    destination = output / "My-AI" / "Vaswani - 2017 - Attention Is All You Need.pdf"
    manifest_path = output / "My-AI" / ".zpm" / "manifest.json"
    manifest_before = manifest_path.read_bytes()
    _remove_root_item(fixture.database)  # type: ignore[attr-defined]

    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        stats = CollectionExporter(database, output, prune=True, dry_run=True).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )[0]

    assert stats.pruned == 1
    assert destination.is_file()
    assert manifest_path.read_bytes() == manifest_before


def test_first_discovered_attachment_can_be_missing(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    fixture.second_pdf.unlink()  # type: ignore[attr-defined]
    output = tmp_path / "exports"
    stats = _sync_once(output, fixture)
    manifest = load_manifest(output / "My-AI" / ".zpm" / "manifest.json")
    assert stats.missing == 1
    assert manifest is not None
    assert any(entry.attachment_key == "ATTACH02" and entry.state == "missing" for entry in manifest.items)


def test_prune_protects_modified_removed_file(tmp_path: Path, zotero_fixture: object) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    destination = output / "My-AI" / "Vaswani - 2017 - Attention Is All You Need.pdf"
    destination.write_bytes(b"user-edited-export")
    _remove_root_item(fixture.database)  # type: ignore[attr-defined]

    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        stats = CollectionExporter(database, output, prune=True).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )[0]

    assert stats.pruned == 0
    assert stats.protected == 1
    assert destination.read_bytes() == b"user-edited-export"
    manifest = load_manifest(output / "My-AI" / ".zpm" / "manifest.json")
    assert manifest is not None
    assert any(entry.state == "removed" for entry in manifest.items)


def test_readded_identical_attachment_reuses_managed_destination(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    original_destination = output / "My-AI" / "Vaswani - 2017 - Attention Is All You Need.pdf"
    _remove_root_item(fixture.database)  # type: ignore[attr-defined]
    _sync_once(output, fixture)

    new_source = fixture.data_dir / "storage" / "ATTACH03" / "attention-new.pdf"  # type: ignore[attr-defined]
    new_source.parent.mkdir(parents=True)
    new_source.write_bytes(fixture.second_pdf.read_bytes())  # type: ignore[attr-defined]
    connection = sqlite3.connect(fixture.database)  # type: ignore[attr-defined]
    connection.executemany(
        "INSERT INTO items (itemID, key) VALUES (?, ?)",
        [(300, "ITEM0003"), (301, "ATTACH03")],
    )
    connection.execute("INSERT INTO collectionItems VALUES (?, ?)", (1, 300))
    connection.execute(
        "INSERT INTO itemAttachments VALUES (?, ?, ?, ?)",
        (301, 300, "application/pdf", "storage:attention-new.pdf"),
    )
    connection.commit()
    connection.close()

    stats = _sync_once(output, fixture)
    manifest = load_manifest(output / "My-AI" / ".zpm" / "manifest.json")
    assert stats.reconciled == 1
    assert original_destination.is_file()
    assert len(list((output / "My-AI").glob("*.pdf"))) == 1
    assert manifest is not None
    assert any(entry.attachment_key == "ATTACH03" for entry in manifest.items)
    assert not any(entry.attachment_key == "ATTACH02" for entry in manifest.items)


def test_readded_attachment_does_not_reconcile_with_modified_stale_export(
    tmp_path: Path, zotero_fixture: object
) -> None:
    fixture = zotero_fixture
    output = tmp_path / "exports"
    _initial_export(output, fixture)
    stale = output / "My-AI" / "Vaswani - 2017 - Attention Is All You Need.pdf"
    _remove_root_item(fixture.database)  # type: ignore[attr-defined]
    _sync_once(output, fixture)
    stale.write_bytes(b"user-modified-stale-file")

    new_source = fixture.data_dir / "storage" / "ATTACH03" / "attention-new.pdf"  # type: ignore[attr-defined]
    new_source.parent.mkdir(parents=True)
    new_source.write_bytes(fixture.second_pdf.read_bytes())  # type: ignore[attr-defined]
    connection = sqlite3.connect(fixture.database)  # type: ignore[attr-defined]
    connection.executemany(
        "INSERT INTO items (itemID, key) VALUES (?, ?)",
        [(300, "ITEM0003"), (301, "ATTACH03")],
    )
    connection.execute("INSERT INTO collectionItems VALUES (?, ?)", (1, 300))
    connection.execute(
        "INSERT INTO itemAttachments VALUES (?, ?, ?, ?)",
        (301, 300, "application/pdf", "storage:attention-new.pdf"),
    )
    connection.commit()
    connection.close()

    stats = _sync_once(output, fixture)
    assert stats.reconciled == 0
    assert stale.read_bytes() == b"user-modified-stale-file"
    assert len(list((output / "My-AI").glob("*.pdf"))) == 2


def _initial_export(output: Path, fixture: object) -> None:
    _sync_once(output, fixture)


def _sync_once(output: Path, fixture: object):
    with ZoteroDatabase(fixture.data_dir, database_path=fixture.database) as database:  # type: ignore[attr-defined]
        records = database.list_collections()
        return CollectionExporter(database, output).export_many(
            [resolve_collection(records, "My-AI")], build_collection_forest(records)
        )[0]


def _remove_root_item(database_path: Path) -> None:
    connection = sqlite3.connect(database_path)
    connection.execute("DELETE FROM collectionItems WHERE collectionID = 1 AND itemID = 200")
    connection.commit()
    connection.close()
