"""Safe Markdown export for Zotero annotations and child notes."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import quote

from .filenames import extract_year
from .models import Collection, ZoteroAnnotation, ZoteroAttachment, ZoteroNote
from .utils import atomic_copy_file, atomic_write_text, is_within, sha256_file

ANNOTATION_MARKER = "<!-- Generated by zpm; changes will be replaced. -->"
ANNOTATION_ASSET_MARKER = "Generated by zpm; image assets may be replaced.\n"
ANNOTATION_LAYOUTS = ("separate", "sidecar", "bundle")
DEFAULT_ANNOTATION_LAYOUT = "separate"
_SPACE = re.compile(r"[ \t]+")
_BLANK_LINES = re.compile(r"\n{3,}")
_SAFE_KEY = re.compile(r"[^A-Za-z0-9_-]+")


class AnnotationError(RuntimeError):
    """Raised when generated annotation files cannot be updated safely."""


def validate_annotation_layout(value: str) -> str:
    """Validate and normalize an annotation workspace layout name."""

    normalized = value.strip().casefold()
    if normalized not in ANNOTATION_LAYOUTS:
        choices = ", ".join(ANNOTATION_LAYOUTS)
        raise ValueError(f"Unknown annotation layout {value!r}; choose one of: {choices}")
    return normalized


@dataclass(frozen=True, slots=True)
class AnnotationDocument:
    """One generated annotation Markdown document."""

    relative_path: Path
    content: str
    annotation_count: int
    note_count: int
    images: tuple["AnnotationImage", ...] = ()


@dataclass(frozen=True, slots=True)
class AnnotationImage:
    """One cached Zotero annotation image copied into the workspace."""

    source_path: Path
    relative_path: Path


class _NoteHTMLParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []
        self.hidden_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in {"script", "style"}:
            self.hidden_depth += 1
            return
        if self.hidden_depth:
            return
        if tag == "br":
            self.parts.append("\n")
        elif tag == "li":
            self.parts.append("\n- ")
        elif tag in {"p", "div", "blockquote", "h1", "h2", "h3", "h4", "h5", "h6"}:
            self.parts.append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag in {"script", "style"}:
            self.hidden_depth = max(0, self.hidden_depth - 1)
            return
        if not self.hidden_depth and tag in {
            "p",
            "div",
            "li",
            "blockquote",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
        }:
            self.parts.append("\n")

    def handle_data(self, data: str) -> None:
        if not self.hidden_depth:
            self.parts.append(data)


def note_html_to_markdown(value: str) -> str:
    """Convert Zotero note HTML to conservative, readable Markdown text."""

    parser = _NoteHTMLParser()
    parser.feed(value)
    parser.close()
    lines = [_SPACE.sub(" ", line).strip() for line in "".join(parser.parts).splitlines()]
    normalized = "\n".join(lines).strip()
    return _BLANK_LINES.sub("\n\n", normalized)


def render_annotation_document(
    collection: Collection,
    attachment: ZoteroAttachment,
    annotations: tuple[ZoteroAnnotation, ...],
    notes: tuple[ZoteroNote, ...],
    *,
    pdf_relative_path: Path,
    annotation_relative_path: Path,
    include_images: bool = True,
) -> AnnotationDocument:
    """Render annotations and child notes for one exported attachment."""

    title = attachment.title or pdf_relative_path.stem
    relative_pdf_link = Path(
        os.path.relpath(pdf_relative_path, start=annotation_relative_path.parent)
    ).as_posix()
    images: list[AnnotationImage] = []
    asset_directory_name = f"{annotation_relative_path.stem}.assets"
    lines = [
        ANNOTATION_MARKER,
        "",
        f"# {title}",
        "",
        f"- Zotero item key: `{attachment.item_key}`",
        f"- Zotero attachment key: `{attachment.attachment_key}`",
    ]
    if attachment.creators:
        lines.append(f"- Creators: {', '.join(attachment.creators)}")
    year = extract_year(attachment.date)
    if year:
        lines.append(f"- Year: {year}")
    if attachment.doi:
        lines.append(f"- DOI: {attachment.doi}")
    if attachment.tags:
        lines.append(f"- Item tags: {', '.join(attachment.tags)}")
    lines.append(
        f"- Exported file: [{pdf_relative_path.name}]("
        f"{quote(relative_pdf_link, safe='/')})"
    )
    if collection.library_id == 1:
        lines.append(
            "- Open in Zotero: "
            f"[PDF](zotero://open-pdf/library/items/{attachment.attachment_key})"
        )

    lines.extend(["", "## Annotations", ""])
    if not annotations:
        lines.extend(["_No PDF annotations found._", ""])
    for annotation in annotations:
        location = f"Page {annotation.page_label}" if annotation.page_label else "Unnumbered page"
        lines.extend([f"### {location} — {annotation.annotation_type.title()}", ""])
        details: list[str] = []
        if annotation.color:
            details.append(f"Color: `{annotation.color}`")
        if annotation.author_name:
            details.append(f"Author: {annotation.author_name}")
        if annotation.tags:
            details.append(f"Tags: {', '.join(annotation.tags)}")
        details.append(f"Modified: {annotation.date_modified}")
        lines.extend(f"- {detail}" for detail in details)
        if annotation.text:
            lines.extend(["", *_blockquote(annotation.text)])
        if annotation.comment:
            lines.extend(["", "**Comment**", "", annotation.comment.strip()])
        if annotation.image_path and include_images:
            image_name = _annotation_image_name(annotation)
            image_relative_path = (
                annotation_relative_path.parent / asset_directory_name / image_name
            )
            images.append(
                AnnotationImage(
                    source_path=annotation.image_path,
                    relative_path=image_relative_path,
                )
            )
            image_link = Path(asset_directory_name, image_name).as_posix()
            image_alt = f"{location} {annotation.annotation_type} annotation"
            lines.extend(["", f"![{image_alt}]({quote(image_link, safe='/')})"])
        elif annotation.annotation_type in {"image", "ink"} and include_images:
            lines.extend(
                ["", "_Image preview is unavailable in Zotero's local cache._"]
            )
        if collection.library_id == 1:
            lines.extend(
                [
                    "",
                    "[Open annotation in Zotero]("
                    "zotero://open-pdf/library/items/"
                    f"{attachment.attachment_key}?annotation={annotation.annotation_key})",
                ]
            )
        lines.append("")

    lines.extend(["## Child notes", ""])
    if not notes:
        lines.extend(["_No child notes found._", ""])
    for index, note in enumerate(notes, start=1):
        lines.extend([f"### {note.title or f'Note {index}'}", ""])
        lines.append(f"- Modified: {note.date_modified}")
        if note.tags:
            lines.append(f"- Tags: {', '.join(note.tags)}")
        content = note_html_to_markdown(note.content)
        lines.extend(["", content or "_Empty note._", ""])

    return AnnotationDocument(
        relative_path=annotation_relative_path,
        content="\n".join(lines).rstrip() + "\n",
        annotation_count=len(annotations),
        note_count=len(notes),
        images=tuple(images),
    )


def write_annotation_documents(workspace: Path, documents: list[AnnotationDocument]) -> None:
    """Write generated annotation documents and remove obsolete generated documents."""

    validate_annotation_documents(workspace, documents)
    root = workspace
    targets = {document.relative_path for document in documents}
    image_targets = {
        image.relative_path for document in documents for image in document.images
    }
    for document in documents:
        target = workspace / document.relative_path
        if not target.exists() or target.read_text(encoding="utf-8") != document.content:
            atomic_write_text(target, document.content)
        for image in document.images:
            destination = workspace / image.relative_path
            marker = destination.parent / ".zpm-generated"
            if not marker.exists():
                atomic_write_text(marker, ANNOTATION_ASSET_MARKER)
            if not destination.exists() or sha256_file(destination) != sha256_file(
                image.source_path
            ):
                atomic_copy_file(image.source_path, destination)

    if root.exists():
        for candidate in root.rglob("*.md"):
            relative = candidate.relative_to(workspace)
            if relative not in targets and _is_generated(candidate):
                candidate.unlink()
        for asset_directory in root.rglob("*.assets"):
            if not asset_directory.is_dir() or not _is_generated_asset_directory(
                asset_directory
            ):
                continue
            for candidate in asset_directory.glob("*.png"):
                if candidate.relative_to(workspace) not in image_targets:
                    candidate.unlink()
        for directory in sorted(
            (path for path in root.rglob("*") if path.is_dir()),
            key=lambda path: len(path.parts),
            reverse=True,
        ):
            try:
                directory.rmdir()
            except OSError:
                pass


def validate_annotation_documents(
    workspace: Path, documents: list[AnnotationDocument]
) -> None:
    """Validate every generated annotation destination before an export writes files."""

    root = workspace
    if root.is_symlink():
        raise AnnotationError(f"Refusing workspace symlink: {root}")
    for document in documents:
        target = workspace / document.relative_path
        if not is_within(target, workspace):
            raise AnnotationError(f"Annotation path resolves outside workspace: {target}")
        _validate_generated_target(target)
        for image in document.images:
            source = image.source_path
            destination = workspace / image.relative_path
            if not source.is_file() or source.suffix.casefold() != ".png":
                raise AnnotationError(f"Annotation image is not a readable PNG: {source}")
            if not is_within(destination, workspace):
                raise AnnotationError(
                    f"Annotation image path resolves outside workspace: {destination}"
                )
            if destination.is_symlink() or destination.parent.is_symlink():
                raise AnnotationError(f"Refusing annotation image symlink: {destination}")
            if destination.parent.exists() and not _is_generated_asset_directory(
                destination.parent
            ):
                raise AnnotationError(
                    "Refusing to manage an existing annotation asset directory without "
                    f"zpm's safety marker: {destination.parent}"
                )


def _validate_generated_target(path: Path) -> None:
    if path.exists() and not _is_generated(path):
        raise AnnotationError(f"Refusing to replace unmanaged annotation file: {path}")


def _is_generated(path: Path) -> bool:
    try:
        return path.read_text(encoding="utf-8").splitlines()[0] == ANNOTATION_MARKER
    except (OSError, UnicodeError, IndexError):
        return False


def _is_generated_asset_directory(path: Path) -> bool:
    marker = path / ".zpm-generated"
    try:
        return marker.read_text(encoding="utf-8") == ANNOTATION_ASSET_MARKER
    except (OSError, UnicodeError):
        return False


def _annotation_image_name(annotation: ZoteroAnnotation) -> str:
    key = _SAFE_KEY.sub("-", annotation.annotation_key).strip("-_")
    return f"{key or f'annotation-{annotation.annotation_id}'}.png"


def _blockquote(value: str) -> list[str]:
    lines = value.strip().splitlines() or [""]
    return [f"> {line}" if line else ">" for line in lines]
