"""Gemini Notebook (NotebookLM) export-profile helpers."""

from __future__ import annotations

from pathlib import Path
from urllib.parse import quote

from .annotations import AnnotationDocument
from .metadata import MetadataEntry
from .utils import atomic_write_text

STANDARD_PROFILE = "standard"
NOTEBOOKLM_PROFILE = "notebooklm"
EXPORT_PROFILES = (STANDARD_PROFILE, NOTEBOOKLM_PROFILE)
NOTEBOOKLM_WORKSPACE_SUFFIX = " - NotebookLM"
NOTEBOOKLM_OVERVIEW_FILENAME = "collection-overview.md"
NOTEBOOKLM_OVERVIEW_MARKER = (
    "<!-- Generated by zpm for Gemini Notebook; changes will be replaced. -->"
)
NOTEBOOKLM_DEFAULT_SOURCE_LIMIT = 50

# Supported local-source types in the consumer Gemini Notebook product. Keep the
# extension list explicit so arbitrary zpm control files and data attachments do
# not leak into a prepared notebook folder merely because non-PDF export is enabled.
NOTEBOOKLM_SUPPORTED_EXTENSIONS = frozenset(
    {
        ".3g2",
        ".3gp",
        ".aac",
        ".aif",
        ".aifc",
        ".aiff",
        ".amr",
        ".au",
        ".avi",
        ".avif",
        ".bmp",
        ".cda",
        ".csv",
        ".docx",
        ".epub",
        ".gif",
        ".heic",
        ".heif",
        ".ico",
        ".jp2",
        ".jpe",
        ".jpeg",
        ".jpg",
        ".m4a",
        ".markdown",
        ".md",
        ".mid",
        ".midi",
        ".mp3",
        ".mp4",
        ".mpeg",
        ".ogg",
        ".opus",
        ".pdf",
        ".png",
        ".pptx",
        ".ra",
        ".ram",
        ".snd",
        ".tif",
        ".tiff",
        ".txt",
        ".wav",
        ".weba",
        ".webp",
        ".wma",
    }
)


class NotebookProfileError(ValueError):
    """Raised when a Gemini Notebook profile setting or target is unsafe."""


def validate_export_profile(value: str) -> str:
    """Validate and normalize a workspace export profile."""

    normalized = value.strip().casefold()
    if normalized not in EXPORT_PROFILES:
        choices = ", ".join(EXPORT_PROFILES)
        raise NotebookProfileError(
            f"Unknown export profile {value!r}; choose one of: {choices}"
        )
    return normalized


def is_notebooklm_supported(
    source_path: Path | None,
    original_path: str,
) -> bool:
    """Return whether an attachment is useful as a Gemini Notebook source."""

    candidate = source_path or Path(original_path)
    return candidate.suffix.casefold() in NOTEBOOKLM_SUPPORTED_EXTENSIONS


def validate_notebooklm_overview(workspace: Path) -> None:
    """Refuse to replace a user-owned file at the generated overview path."""

    target = workspace / NOTEBOOKLM_OVERVIEW_FILENAME
    if not target.exists():
        return
    try:
        first_line = target.read_text(encoding="utf-8").splitlines()[0]
    except (OSError, UnicodeError, IndexError) as exc:
        raise NotebookProfileError(
            f"Refusing to replace unmanaged Gemini Notebook overview: {target}"
        ) from exc
    if first_line != NOTEBOOKLM_OVERVIEW_MARKER:
        raise NotebookProfileError(
            f"Refusing to replace unmanaged Gemini Notebook overview: {target}"
        )


def notebooklm_source_count(
    entries: list[MetadataEntry],
    annotation_documents: list[AnnotationDocument],
) -> int:
    """Count primary source files a user can select in the prepared folder."""

    return (
        sum(entry.state == "active" for entry in entries)
        + len(annotation_documents)
        + 1  # collection-overview.md
    )


def write_notebooklm_overview(
    workspace: Path,
    *,
    collection_name: str,
    collection_key: str,
    exported_at: str,
    entries: list[MetadataEntry],
    annotation_documents: list[AnnotationDocument],
) -> int:
    """Write a human-readable root source guide and return its source count."""

    validate_notebooklm_overview(workspace)
    active = sorted(
        (entry for entry in entries if entry.state == "active"),
        key=lambda entry: entry.destination_path.casefold(),
    )
    documents = sorted(
        annotation_documents,
        key=lambda document: document.relative_path.as_posix().casefold(),
    )
    source_count = notebooklm_source_count(entries, annotation_documents)
    lines = [
        NOTEBOOKLM_OVERVIEW_MARKER,
        "",
        f"# {collection_name} — Gemini Notebook sources",
        "",
        "This folder was prepared by Zotero Project Manager for import into "
        "Gemini Notebook (formerly NotebookLM).",
        "",
        f"- Zotero collection key: `{collection_key}`",
        f"- Exported: {exported_at}",
        f"- Prepared source files: {source_count}",
        "",
        "Select the files you want from this folder in **Add sources → Google Drive**. "
        "The `.zpm` directory contains zpm bookkeeping and should not be imported.",
        "",
    ]
    if source_count > NOTEBOOKLM_DEFAULT_SOURCE_LIMIT:
        lines.extend(
            [
                "> This folder contains more than 50 prepared sources. Select a subset "
                "if it exceeds your Gemini Notebook plan's current source limit.",
                "",
            ]
        )
    lines.extend(
        [
            "## Attachments",
            "",
            "| Title | Creators | File |",
            "| --- | --- | --- |",
        ]
    )
    for entry in active:
        title = _cell(entry.title or Path(entry.destination_path).stem)
        creators = _cell(", ".join(entry.creators) or "—")
        link = quote(entry.destination_path, safe="/")
        name = _cell(Path(entry.destination_path).name)
        lines.append(f"| {title} | {creators} | [{name}]({link}) |")
    if not active:
        lines.append("| — | — | _No available supported attachments_ |")

    lines.extend(["", "## Annotation notes", ""])
    if documents:
        for document in documents:
            path = document.relative_path.as_posix()
            name = _cell(document.relative_path.name)
            lines.append(f"- [{name}]({quote(path, safe='/')})")
    else:
        lines.append("_No annotation documents were generated._")
    lines.append("")

    atomic_write_text(
        workspace / NOTEBOOKLM_OVERVIEW_FILENAME,
        "\n".join(lines),
    )
    return source_count


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()
