"""Workspace metadata JSON and human-readable Markdown index generation."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from urllib.parse import quote

from .filenames import extract_year
from .manifest import Manifest
from .utils import atomic_write_text

INDEX_MARKER = "<!-- Generated by zpm; changes will be replaced. -->"


class MetadataError(RuntimeError):
    """Raised when a metadata artifact cannot be updated safely."""


@dataclass(frozen=True, slots=True)
class MetadataEntry:
    """Research metadata for one current Zotero attachment."""

    collection_key: str
    item_key: str
    attachment_key: str
    title: str | None
    date: str | None
    creators: tuple[str, ...]
    doi: str | None
    tags: tuple[str, ...]
    content_type: str | None
    source_path: str
    destination_path: str
    state: str
    sha256: str | None


def write_metadata_files(
    control_directory: Path,
    manifest: Manifest,
    entries: list[MetadataEntry],
) -> None:
    """Atomically write ``metadata.json`` and ``INDEX.md`` under zpm control data."""

    validate_metadata_targets(control_directory)
    ordered = sorted(entries, key=lambda entry: entry.destination_path.casefold())
    payload = {
        "generated_by": "zpm",
        "schema_version": 1,
        "generated_at": manifest.exported_at,
        "collection_key": manifest.collection_key,
        "collection_name": manifest.collection_name,
        "items": [asdict(entry) for entry in ordered],
    }
    atomic_write_text(
        control_directory / "metadata.json",
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )
    atomic_write_text(control_directory / "INDEX.md", _markdown_index(manifest, ordered))


def _markdown_index(manifest: Manifest, entries: list[MetadataEntry]) -> str:
    lines = [
        INDEX_MARKER,
        "",
        f"# {manifest.collection_name}",
        "",
        f"Generated from Zotero collection `{manifest.collection_key}` at "
        f"{manifest.exported_at}.",
        "",
        "| Title | Creators | Year | DOI | Tags | File |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for entry in entries:
        title = _cell(entry.title or Path(entry.destination_path).stem)
        creators = _cell(", ".join(entry.creators) or "—")
        year = extract_year(entry.date) or "—"
        doi = (
            f"[{_cell(entry.doi)}](https://doi.org/{quote(entry.doi, safe='/')})"
            if entry.doi
            else "—"
        )
        tags = _cell(", ".join(entry.tags) or "—")
        suffix = Path(entry.destination_path).suffix.lstrip(".").upper()
        file_label = suffix or "File"
        file_link = (
            f"[{file_label}]({quote('../' + entry.destination_path, safe='/')})"
            if entry.state == "active"
            else f"_{_cell(entry.state)}_"
        )
        lines.append(f"| {title} | {creators} | {year} | {doi} | {tags} | {file_link} |")
    lines.append("")
    return "\n".join(lines)


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def validate_metadata_targets(control_directory: Path) -> None:
    """Refuse to overwrite metadata filenames not previously generated by zpm."""

    metadata_path = control_directory / "metadata.json"
    if metadata_path.exists():
        try:
            payload = json.loads(metadata_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise MetadataError(
                f"Refusing to replace unmanaged metadata file: {metadata_path}"
            ) from exc
        if not isinstance(payload, dict) or payload.get("generated_by") != "zpm":
            raise MetadataError(f"Refusing to replace unmanaged metadata file: {metadata_path}")
    index_path = control_directory / "INDEX.md"
    if index_path.exists():
        try:
            first_line = index_path.read_text(encoding="utf-8").splitlines()[0]
        except (OSError, IndexError) as exc:
            raise MetadataError(f"Refusing to replace unmanaged index file: {index_path}") from exc
        if first_line != INDEX_MARKER:
            raise MetadataError(f"Refusing to replace unmanaged index file: {index_path}")
