;;; org-picker.test.el --- Picker tests -*- lexical-binding: t; -*-
(require 'ert)
(load-file "docs/emacs/zpm-org-picker.el")
(defconst zpm-test-payload
  '((schema . 1) (collection . ((key . "6RIU3F76") (name . "scientometry")))
    (papers . (((key . "ABCD2345") (title . "Paper [one]\nnext") (authors . "Heidler") (year . "2015"))
               ((key . "EFGH6789") (title . "Paper [one]\nnext") (authors . "Heidler") (year . "2015"))))))

(ert-deftest zpm-picker-inserts-selected-record-in-sentence ()
  (with-temp-buffer
    (org-mode) (insert "Read  next.") (goto-char 6)
    (cl-letf (((symbol-function 'zpm--request) (lambda (&optional _) zpm-test-payload))
              ((symbol-function 'completing-read)
               (lambda (_prompt candidates &rest _) (caar (last candidates)))))
      (zpm-insert-paper-link))
    (should (equal (buffer-string) "Read [[zotero-item:EFGH6789?collection=6RIU3F76][Paper ［one］ next]] next."))))

(ert-deftest zpm-picker-open-exact-process-arguments-and-no-buffer-edit ()
  (with-temp-buffer
    (org-mode) (insert "Notes")
    (let ((system-type 'darwin)
          calls)
      (cl-letf (((symbol-function 'zpm--request) (lambda (&optional _) zpm-test-payload))
                ((symbol-function 'completing-read) (lambda (_ candidates &rest _) (caar candidates)))
                ((symbol-function 'start-process) (lambda (&rest args) (push args calls))))
        (zpm-open-paper))
      (should (equal calls '(("zpm-paper" nil "/usr/bin/open" "zotero://select/library/collections/6RIU3F76/items/ABCD2345"))))
      (should (equal (buffer-string) "Notes")))))

(ert-deftest zpm-picker-remember-forget-and-use-note-collection ()
  (with-temp-buffer
    (org-mode) (insert "#+TITLE: Notes\nBody\n")
    (cl-letf (((symbol-function 'zpm--request) (lambda (&optional _) zpm-test-payload)))
      (zpm-remember-collection))
    (should (equal (zpm--remembered-collection) "6RIU3F76"))
    (let (requested)
      (cl-letf (((symbol-function 'zpm--request) (lambda (&optional key) (setq requested key) zpm-test-payload))
                ((symbol-function 'completing-read) (lambda (_ candidates &rest _) (caar candidates))))
        (zpm--pick))
      (should (equal requested "6RIU3F76")))
    (zpm-forget-collection)
    (should-not (zpm--remembered-collection))
    (should (equal (buffer-string) "#+TITLE: Notes\nBody\n"))))

(ert-deftest zpm-picker-invalid-note-collection-and-cancel-leave-buffer-alone ()
  (with-temp-buffer
    (org-mode) (insert "#+ZPM_COLLECTION: nil\n")
    (should-error (zpm-insert-paper-link) :type 'user-error)
    (should (equal (buffer-string) "#+ZPM_COLLECTION: nil\n"))
    (erase-buffer) (insert "Notes")
    (cl-letf (((symbol-function 'zpm--request) (lambda (&optional _) zpm-test-payload))
              ((symbol-function 'completing-read) (lambda (&rest _) (signal 'quit nil))))
      (should (eq (condition-case nil (zpm-insert-paper-link) (quit 'cancelled)) 'cancelled)))
    (should (equal (buffer-string) "Notes"))))

(ert-deftest zpm-picker-empty-or-malformed-data-rejected ()
  (should-error (zpm--choose-paper '((papers . nil))) :type 'user-error)
  (let ((bad (copy-tree zpm-test-payload)))
    (setcdr (assq 'key (car (alist-get 'papers bad))) "nil")
    (should-error (zpm--choose-paper bad) :type 'user-error))
  (with-temp-buffer
    (org-mode) (insert "#+ZPM_COLLECTION: 6RIU3F76\n#+ZPM_COLLECTION: ABCD2345\n")
    (should-error (zpm--remembered-collection) :type 'user-error)))

(ert-deftest zpm-picker-http-request-is-loopback-get-with-bounded-timeout ()
  (let (response args)
    (cl-letf (((symbol-function 'url-retrieve-synchronously)
               (lambda (url silent cookies timeout)
                 (setq args (list url silent cookies timeout url-request-method url-request-extra-headers url-max-redirections url-proxy-services))
                 (setq response (generate-new-buffer " *zpm-test*"))
                 (with-current-buffer response
                   (setq-local url-http-response-status 200)
                   (insert "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n" (json-encode zpm-test-payload)))
                 response)))
      (should (equal (zpm--request "6RIU3F76") zpm-test-payload)))
    (should-not (buffer-live-p response))
    (should (equal args '("http://127.0.0.1:23119/zpm/papers?collection=6RIU3F76" t t 5 "GET"
                          (("X-ZPM-Client" . "emacs") ("Accept" . "application/json")
                           ("Zotero-Allowed-Request" . "true")) 0 nil)))))

(ert-deftest zpm-picker-http-failures-are-useful-and-clean-up ()
  (cl-letf (((symbol-function 'url-retrieve-synchronously) (lambda (&rest _) nil)))
    (should-error (zpm--request) :type 'user-error))
  (dolist (status '(403 404 409 500 302))
    (let (response)
      (cl-letf (((symbol-function 'url-retrieve-synchronously)
                 (lambda (&rest _)
                   (setq response (generate-new-buffer " *zpm-test-error*"))
                   (with-current-buffer response
                     (setq-local url-http-response-status status)
                     (insert "HTTP/1.1 Error\r\n\r\n{\"error\":\"Fixture failure\"}")) response)))
        (should-error (zpm--request) :type 'user-error))
      (should-not (buffer-live-p response)))))

(ert-deftest zpm-picker-no-edits-outside-org-or-in-read-only-note ()
  (with-temp-buffer (should-error (zpm-insert-paper-link) :type 'user-error))
  (with-temp-buffer
    (org-mode) (setq buffer-read-only t)
    (should-error (zpm-insert-paper-link) :type 'buffer-read-only)
    (should-error (zpm-remember-collection) :type 'buffer-read-only)))

(ert-deftest zpm-picker-note-setting-survives-narrowing-and-preserves-examples ()
  (with-temp-buffer
    (org-mode)
    (insert "#+ZPM_COLLECTION: 6RIU3F76\n* Notes\nText\n#+begin_example\n#+ZPM_COLLECTION: ABCD2345\n#+end_example\n")
    (goto-char (point-min)) (search-forward "* Notes")
    (narrow-to-region (line-beginning-position) (point-max))
    (should (equal (zpm--remembered-collection) "6RIU3F76"))
    (zpm-forget-collection)
    (should-not (zpm--remembered-collection))
    (widen)
    (should (string-match-p "#\\+ZPM_COLLECTION: ABCD2345" (buffer-string)))
    (should-not (string-match-p "6RIU3F76" (buffer-string)))))

(ert-deftest zpm-picker-decodes-real-http-utf8-bytes ()
  (dolist (status '(200 403))
    (let* ((text "Settings → Advanced: ‘İstanbul 文献’")
           (payload (if (= status 200)
                        `((schema . 1) (collection . ((key . "6RIU3F76") (name . ,text))) (papers . nil))
                      `((error . ,text)))))
      (cl-letf (((symbol-function 'url-retrieve-synchronously)
                 (lambda (&rest _)
                   (let ((buffer (generate-new-buffer " *zpm-utf8*")))
                     (with-current-buffer buffer
                       (set-buffer-multibyte nil)
                       (setq-local url-http-response-status status)
                       (insert "HTTP/1.1 response\r\nContent-Type: application/json\r\n\r\n"
                               (encode-coding-string (json-encode payload) 'utf-8)))
                     buffer))))
        (if (= status 200)
            (should (equal (alist-get 'name (alist-get 'collection (zpm--request))) text))
          (should (equal (cadr (should-error (zpm--request) :type 'user-error)) text)))))))

(ert-deftest zpm-picker-permission-help-is-offered-without-changing-note ()
  (dolist (answer '(t nil))
    (with-temp-buffer
      (org-mode) (insert "My notes")
      (let (asked shown)
        (cl-letf (((symbol-function 'zpm--request)
                   (lambda (&optional _) (signal 'zpm-local-api-disabled '("Enable local access"))))
                  ((symbol-function 'y-or-n-p) (lambda (_) (setq asked t) answer))
                  ((symbol-function 'zpm-picker-setup) (lambda () (setq shown t))))
          (should-error (zpm-insert-paper-link) :type 'user-error))
        (should asked) (should (eq shown answer))
        (should (equal (buffer-string) "My notes"))))))

(ert-deftest zpm-picker-detects-only-the-local-permission-error ()
  (dolist (payload '(((code . "local_api_disabled") (error . "Enable local API"))
                    ((error . "In Zotero Settings → Advanced, enable ‘Allow other applications on this computer to communicate with Zotero’."))))
    (cl-letf (((symbol-function 'url-retrieve-synchronously)
               (lambda (&rest _)
                 (let ((buffer (generate-new-buffer " *zpm-permission*")))
                   (with-current-buffer buffer
                     (set-buffer-multibyte nil)
                     (setq-local url-http-response-status 403)
                     (insert "HTTP/1.1 403 Forbidden\r\n\r\n" (encode-coding-string (json-encode payload) 'utf-8)))
                   buffer))))
      (should-error (zpm--request) :type 'zpm-local-api-disabled))))

(ert-run-tests-batch-and-exit)
